//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sequoia_BE {
    
    
    public partial class InvDoWithOutletPO {
        
        /// <summary>
        /// txtInvNo_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtInvNo_InvDoWithOutletPO;
        
        /// <summary>
        /// txtDocNo_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtDocNo_InvDoWithOutletPO;
        
        /// <summary>
        /// dt_DocDateInvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText dt_DocDateInvDoWithOutletPO;
        
        /// <summary>
        /// ddl_supplierInvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect ddl_supplierInvDoWithOutletPO;
        
        /// <summary>
        /// txtTotQty_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtTotQty_InvDoWithOutletPO;
        
        /// <summary>
        /// ddlStoreCode_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect ddlStoreCode_InvDoWithOutletPO;
        
        /// <summary>
        /// txtStatus_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtStatus_InvDoWithOutletPO;
        
        /// <summary>
        /// txtRemark_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtRemark_InvDoWithOutletPO;
        
        /// <summary>
        /// InvDoWithOutletPOEntryModule control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable InvDoWithOutletPOEntryModule;
        
        /// <summary>
        /// txt_TotAmntInvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputGenericControl txt_TotAmntInvDoWithOutletPO;
        
        /// <summary>
        /// txtAttnTo_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtAttnTo_InvDoWithOutletPO;
        
        /// <summary>
        /// txtAddress1_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtAddress1_InvDoWithOutletPO;
        
        /// <summary>
        /// txtShipToAddress1_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtShipToAddress1_InvDoWithOutletPO;
        
        /// <summary>
        /// txtAddress2_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtAddress2_InvDoWithOutletPO;
        
        /// <summary>
        /// txtShipToAddress2_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtShipToAddress2_InvDoWithOutletPO;
        
        /// <summary>
        /// txtAddress3_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtAddress3_InvDoWithOutletPO;
        
        /// <summary>
        /// txtShipToAddress3_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtShipToAddress3_InvDoWithOutletPO;
        
        /// <summary>
        /// txtPostCode_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtPostCode_InvDoWithOutletPO;
        
        /// <summary>
        /// txtPostCodeTo_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtPostCodeTo_InvDoWithOutletPO;
        
        /// <summary>
        /// txtCity_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCity_InvDoWithOutletPO;
        
        /// <summary>
        /// txtCityTo_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCityTo_InvDoWithOutletPO;
        
        /// <summary>
        /// txtState_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtState_InvDoWithOutletPO;
        
        /// <summary>
        /// txtStateTo_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtStateTo_InvDoWithOutletPO;
        
        /// <summary>
        /// txtCountry_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCountry_InvDoWithOutletPO;
        
        /// <summary>
        /// txtCountryTo_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCountryTo_InvDoWithOutletPO;
        
        /// <summary>
        /// txtRemark1_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtRemark1_InvDoWithOutletPO;
        
        /// <summary>
        /// txtRemark2_InvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtRemark2_InvDoWithOutletPO;
        
        /// <summary>
        /// btnSubmit_AddInvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnSubmit_AddInvDoWithOutletPO;
        
        /// <summary>
        /// btnSubmit_PostInvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnSubmit_PostInvDoWithOutletPO;
        
        /// <summary>
        /// btnSubmit_ListInvDoWithOutletPO control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnSubmit_ListInvDoWithOutletPO;
    }
}
